export const APIKEY = 'lmdFUQVnyLK4jA2jRvnLKjqUXfE0mY6G';
export const GIF_LIMIT = 20;
export const BASE_URL = 'https://api.giphy.com/v1/gifs/';
export const MIN_WIDTH_DESKTOP = 768;
export const MAX_WIDTH_DESKTOP = 1600;
export const SCROLL_OFFSET = 200;
export const GIF_PADDING = 10;
export const SEARCH_PATH = 'search?q=';
export const TRENDING_PATH = 'trending'